## Linear Regression 练习

In [380]:
import pandas as pd

## 读取数据

In [244]:
train = pd.read_csv("./all/train.csv")
test = pd.read_csv("./all/test.csv")

## 删除非数字的属性

In [245]:
todrop = []
for column in train.columns:
    if train[column].dtype == 'object':
        todrop.append(column)
    #print(column,' ',data[column].dtype,' ',data[column][0])

In [246]:
train = train.drop(todrop, axis=1)
test = test.drop(todrop, axis=1)

## 补充NULL值

In [247]:
print(train.isnull().sum())
print('-'*50)
print(test.isnull().sum())

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64
--------------------------------------------------
Id                 0
MSSubClass         0
LotFrontage      227
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt   

In [248]:
datasets = [train, test]

In [249]:
for dataset in datasets:
    ret = dataset.isnull().sum()
    for index in ret.index:
        if ret[index] != 0:
            dataset[index].fillna(value=dataset[index].mean(), inplace=True)

In [250]:
print(train.isnull().sum())
print('-'*50)
print(test.isnull().sum())

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64
--------------------------------------------------
Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtU

## 提取资料矩阵

In [251]:
import numpy as np

In [252]:
label = train['SalePrice']

In [253]:
train = train.drop(['SalePrice', 'Id'], axis=1)
testId = test['Id']
test = test.drop('Id', axis=1)

In [254]:
print(train.shape)
print(test.shape)

(1460, 36)
(1459, 36)


In [199]:
train

MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0             60    65.000000     8450            7            5       2003   
1             20    80.000000     9600            6            8       1976   
2             60    68.000000    11250            7            5       2001   
3             70    60.000000     9550            7            5       1915   
4             60    84.000000    14260            8            5       2000   
5             50    85.000000    14115            5            5       1993   
6             20    75.000000    10084            8            5       2004   
7             60    70.049958    10382            7            6       1973   
8             50    51.000000     6120            7            5       1931   
9            190    50.000000     7420            5            6       1939   
10            20    70.000000    11200            5            5       1965   
11            60    85.000000    11924            9            5       2005   
12            20    70.049958    12968            5            6       1962   
13            20    91.000000    10652            7            5       2006   
14            20    70.049958    10920            6            5       1960   
15            45    51.000000     6120            7            8       1929   
16            20    70.049958    11241            6            7       1970   
17            90    72.000000    10791            4            5       1967   
18            20    66.000000    13695            5            5       2004   
19            20    70.000000     7560            5            6       1958   
20            60   101.000000    14215            8            5       2005   
21            45    57.000000     7449            7            7       1930   
22            20    75.000000     9742            8            5       2002   
23           120    44.000000     4224            5            7       1976   
24            20    70.049958     8246            5            8       1968   
25            20   110.000000    14230            8            5       2007   
26            20    60.000000     7200            5            7       1951   
27            20    98.000000    11478            8            5       2007   
28            20    47.000000    16321            5            6       1957   
29            30    60.000000     6324            4            6       1927   
...          ...          ...      ...          ...          ...        ...   
1430          60    60.000000    21930            5            5       2005   
1431         120    70.049958     4928            6            6       1976   
1432          30    60.000000    10800            4            6       1927   
1433          60    93.000000    10261            6            5       2000   
1434          20    80.000000    17400            5            5       1977   
1435          20    80.000000     8400            6            9       1962   
1436          20    60.000000     9000            4            6       1971   
1437          20    96.000000    12444            8            5       2008   
1438          20    90.000000     7407            6            7       1957   
1439          60    80.000000    11584            7            6       1979   
1440          70    79.000000    11526            6            7       1922   
1441         120    70.049958     4426            6            5       2004   
1442          60    85.000000    11003           10            5       2008   
1443          30    70.049958     8854            6            6       1916   
1444          20    63.000000     8500            7            5       2004   
1445          85    70.000000     8400            6            5       1966   
1446          20    70.049958    26142            5            7       1962   
1447          60    80.000000    10000            8            5       1995   
1448          50    70.000000    11767            4     

## 归一化

In [200]:
train = (train - train.mean(0))/train.std(0)
test = (test - test.mean(0))/test.std(0)

In [255]:
train = np.hstack((np.ones((train.shape[0],1)),train))
test = np.hstack((np.ones((test.shape[0],1)),test))

In [151]:
origin_train = train.copy()
train = train[:1000, :]

In [167]:
def cal_cost(theta, x, y):
    return 0.5 * ((x.reshape(1,-1)).dot(theta) - y)**2

def numerical_gradient(theta, x, y):
    dtheta = np.zeros((theta.shape))
    n = theta.shape[0]
    for i in range(n):
        theta[i] += 0.01
        cost_up = cal_cost(theta, x, y)
        theta[i] -= 0.02
        cost_down = cal_cost(theta, x, y)
        dtheta[i] = (cost_up - cost_down) / 0.02
    return dtheta

In [185]:
train = origin_train
theta = np.zeros((37,1))
itern = 1000
m = train.shape[0]
n = train.shape[1]
alpha = 0.0001
cost_history = np.zeros((itern,))
for epoch in range(itern):
    for i in range(m):
        x = train[i,:].reshape(-1,1)
        y = label[i]
        cost = cal_cost(theta, x, y)
        dtheta = np.zeros((theta.shape))
        
        x_dot_theta = (x.reshape(1,-1)).dot(theta)
        dtheta[0,0] = x_dot_theta - y
        for j in range(1,dtheta.shape[0]):
            dtheta[j] = (x_dot_theta - y) * x[j,0]
            #print(dtheta[j])
        #print('+'*40)
        #ng = numerical_gradient(theta, x, y)
        #print(np.hstack((dtheta,ng)))
        theta = theta - alpha * dtheta
        
        cost_history[epoch] += cost
        #print('epoch:%d,cost:%.2f' % (epoch, cost))
    cost_history[epoch] /= m
    #print(dtheta)
    print('epoch_cost:%.2f' % (cost_history[epoch]))

epoch_cost:16033970109.96
epoch_cost:11506896564.20
epoch_cost:8668242014.05
epoch_cost:6619591016.41
epoch_cost:5100097055.16
epoch_cost:3967203118.54
epoch_cost:3121497541.42
epoch_cost:2489855116.40
epoch_cost:2017914339.38
epoch_cost:1665164039.12
epoch_cost:1401391247.76
epoch_cost:1204055412.74
epoch_cost:1056336453.31
epoch_cost:945681010.56
epoch_cost:862718849.40
epoch_cost:800454817.51
epoch_cost:753666133.32
epoch_cost:718452751.47
epoch_cost:691901886.18
epoch_cost:671837684.83
epoch_cost:656634424.45
epoch_cost:645077101.29
epoch_cost:636257382.89
epoch_cost:629495947.37
epoch_cost:624284514.29
epoch_cost:620242570.83
epoch_cost:617085065.60
epoch_cost:614598288.20
epoch_cost:612621858.65
epoch_cost:611035277.55
epoch_cost:609747880.60
epoch_cost:608691334.71
epoch_cost:607814031.57
epoch_cost:607076897.93
epoch_cost:606450263.78
epoch_cost:605911520.53
epoch_cost:605443369.29
epoch_cost:605032509.85
epoch_cost:604668659.05
epoch_cost:604343815.18
epoch_cost:604051706.34
e

epoch_cost:599949349.85
epoch_cost:599949338.80
epoch_cost:599949327.96
epoch_cost:599949317.33
epoch_cost:599949306.90
epoch_cost:599949296.67
epoch_cost:599949286.65
epoch_cost:599949276.81
epoch_cost:599949267.16
epoch_cost:599949257.69
epoch_cost:599949248.40
epoch_cost:599949239.29
epoch_cost:599949230.35
epoch_cost:599949221.57
epoch_cost:599949212.96
epoch_cost:599949204.51
epoch_cost:599949196.22
epoch_cost:599949188.07
epoch_cost:599949180.08
epoch_cost:599949172.24
epoch_cost:599949164.54
epoch_cost:599949156.97
epoch_cost:599949149.55
epoch_cost:599949142.26
epoch_cost:599949135.10
epoch_cost:599949128.07
epoch_cost:599949121.17
epoch_cost:599949114.39
epoch_cost:599949107.73
epoch_cost:599949101.18
epoch_cost:599949094.76
epoch_cost:599949088.45
epoch_cost:599949082.24
epoch_cost:599949076.15
epoch_cost:599949070.16
epoch_cost:599949064.28
epoch_cost:599949058.50
epoch_cost:599949052.82
epoch_cost:599949047.24
epoch_cost:599949041.75
epoch_cost:599949036.36
epoch_cost:59994

epoch_cost:599948691.34
epoch_cost:599948691.26
epoch_cost:599948691.19
epoch_cost:599948691.12
epoch_cost:599948691.05
epoch_cost:599948690.98
epoch_cost:599948690.91
epoch_cost:599948690.84
epoch_cost:599948690.78
epoch_cost:599948690.71
epoch_cost:599948690.65
epoch_cost:599948690.58
epoch_cost:599948690.52
epoch_cost:599948690.46
epoch_cost:599948690.40
epoch_cost:599948690.34
epoch_cost:599948690.28
epoch_cost:599948690.22
epoch_cost:599948690.16
epoch_cost:599948690.10
epoch_cost:599948690.05
epoch_cost:599948689.99
epoch_cost:599948689.93
epoch_cost:599948689.88
epoch_cost:599948689.83
epoch_cost:599948689.77
epoch_cost:599948689.72
epoch_cost:599948689.67
epoch_cost:599948689.62
epoch_cost:599948689.57
epoch_cost:599948689.52
epoch_cost:599948689.47
epoch_cost:599948689.42
epoch_cost:599948689.38
epoch_cost:599948689.33
epoch_cost:599948689.28
epoch_cost:599948689.24
epoch_cost:599948689.19
epoch_cost:599948689.15
epoch_cost:599948689.10
epoch_cost:599948689.06
epoch_cost:59994

In [180]:
#mytest = origin_train[1000:]

In [184]:
result = np.zeros((mytest.shape[0],1))
for i in range(mytest.shape[0]):
    x = mytest[i,:].reshape(-1,1)
    y = label[1000+i]
    cost = cal_cost(theta, x, y)
    result[i,0] = (x.reshape(1,-1)).dot(theta)

print(np.linalg.norm(result-label[1000:].reshape((-1,1))))
print(np.hstack((result,label[1000:].reshape((-1,1)))))
    #print('epoch:%d,cost:%.2f' % (epoch, cost))

933332.4230214623
[[ 39805.18044234  82000.        ]
 [ 62508.05038463  86000.        ]
 [246891.48007492 232000.        ]
 [152143.66385969 136905.        ]
 [222925.52348324 181000.        ]
 [132635.88889567 149900.        ]
 [213428.36181802 163500.        ]
 [ 66722.17808179  88000.        ]
 [241029.16314347 240000.        ]
 [ 97876.32188263 102000.        ]
 [108126.88218091 135000.        ]
 [ 89012.16401298 100000.        ]
 [146088.29814307 165000.        ]
 [101730.55605262  85000.        ]
 [130492.85541507 119200.        ]
 [219395.65060368 227000.        ]
 [222019.62769452 203000.        ]
 [214627.61223215 187500.        ]
 [180100.95984766 160000.        ]
 [207862.04291725 213490.        ]
 [155701.19152756 176000.        ]
 [219302.24550964 194000.        ]
 [116487.26131452  87000.        ]
 [209442.74826622 191000.        ]
 [352823.3092916  287000.        ]
 [109465.32985151 112500.        ]
 [163801.10401952 167500.        ]
 [291693.00086737 293077.        ]
 [

/home/luo3300612/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  
/home/luo3300612/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  if __name__ == '__main__':


In [236]:
result = np.zeros((test.shape[0],1))
for i in range(test.shape[0]):
    x = test[i,:].reshape(-1,1)
    result[i,0] = (x.reshape(1,-1)).dot(theta.reshape((-1,1)))

In [220]:
c = np.array(testId, dtype='int')

In [261]:
ret = pd.DataFrame(columns=['Id', 'SalePrice'])

ret['Id'] = c
ret['SalePrice'] = result

In [228]:
ret.to_csv('ret.csv', index=False)

In [320]:
theta2 = np.linalg.inv(train.T.dot(train)).dot(train.T).dot(label)
print(theta2)

[ 1.43664272e+07  2.00939110e+04  2.87450905e+04 -1.48583062e+01
 -5.30197914e+05 -5.07101592e+04 -3.58007646e+03 -3.54311543e+03
  1.41296983e+02 -6.29271123e+14 -6.29271123e+14 -6.29271123e+14
  6.29271123e+14  6.09069930e+01 -1.08486223e+02 -2.14241693e+02
  2.70801377e+02  9.35912950e+03  2.03772192e+03  3.44826880e+03
 -1.89958357e+03 -1.00959951e+04 -1.22096934e+04  5.06341327e+03
  3.96643044e+03  1.21154692e+02  1.12346410e+04 -4.23646789e+00
  2.40215542e+01 -2.87114196e+00  1.18267942e+01  2.04961726e+01
  5.60046684e+01 -2.90824807e+01 -7.30182383e-01 -5.00874308e+01
 -7.80459754e+02]


In [318]:
(train.T).dot(train).dot(theta2)

array([-6.78100992e+08, -5.01638758e+09, -3.95019551e+10, -7.89307615e+12,
       -4.99541606e+09, -3.95313152e+09, -1.34996191e+12, -1.35546484e+12,
       -8.43977851e+10, -3.44637571e+11, -2.51574354e+10, -4.13994582e+11,
       -7.83563096e+11, -8.19533447e+11, -1.79247776e+11,  3.68155034e+09,
       -9.95224453e+11, -3.12311808e+08, -3.80764160e+07, -1.12420454e+09,
       -2.86162944e+08, -1.78860851e+09, -5.79076096e+08, -4.25407283e+09,
       -5.00236288e+08, -1.35023034e+12, -1.42095155e+09, -3.76447173e+11,
       -8.37602509e+10, -3.93299886e+10, -5.31418317e+09, -2.96484864e+09,
       -1.11117599e+10,  4.29077299e+09, -2.76111032e+10, -4.46955520e+09,
       -1.36110198e+12])

In [328]:
k = ((train.T).dot(train)).dot(np.linalg.inv(train.T.dot(train)))
print(k)

[[ 1.00000000e+00  1.21570986e-15 -1.19517916e-15 ... -2.59772804e-18
  -5.89466931e-14  7.70371722e-14]
 [ 1.18293854e-07  1.00000000e+00 -1.01547409e-14 ... -1.46281162e-16
  -1.40850939e-12  4.94472807e-11]
 [ 6.17428483e-08  3.39077017e-14  1.00000000e+00 ... -3.09531117e-17
  -1.22396851e-12  2.34718893e-11]
 ...
 [ 5.65650216e-08  2.20184150e-14 -4.52307352e-14 ...  1.00000000e+00
  -2.16019346e-12  1.37251784e-11]
 [ 2.20219576e-09  4.69913381e-15  2.04932507e-15 ... -2.02087834e-17
   1.00000000e+00  2.88140085e-12]
 [ 9.53674316e-07  9.09494702e-13 -9.09494702e-13 ... -7.99360578e-15
  -5.82076609e-11  1.00000000e+00]]


In [330]:
print(k.dot(train.T).dot(label))

[-7.19161707e+08 -1.93303314e+09 -1.65302233e+10 -6.83127009e+12
 -6.88274704e+09 -1.14411934e+09 -9.28464485e+11 -1.21591221e+12
 -9.70528351e+10 -2.88997131e+11 -3.28591115e+10 -3.14211816e+11
 -9.03566140e+11 -1.29847500e+12 -1.96369755e+11  4.87839829e+09
 -6.08590291e+11 -1.70303613e+08 -1.40498103e+07 -1.13168524e+09
 -2.57838111e+08 -1.73032184e+09 -5.04981709e+08 -3.92998095e+09
 -1.00058152e+09 -1.26952495e+12 -1.42554663e+09 -4.90042870e+11
 -7.84235561e+10 -3.47830566e+10 -2.12026120e+10 -2.30817412e+09
 -5.98401736e+09  5.00807507e+09 -1.30998789e+10 -7.11306165e+09
 -5.02557863e+12]


In [324]:
(train.T).dot(label)

array([2.64144946e+08, 1.46158857e+10, 1.93582539e+10, 3.08320594e+12,
       1.73789637e+09, 1.46265662e+09, 5.22530944e+11, 5.25505719e+11,
       3.73343366e+10, 1.37613191e+11, 1.20830185e+10, 1.60818300e+11,
       3.10514510e+11, 3.34249040e+11, 1.07813489e+11, 1.39949116e+09,
       4.43462020e+11, 1.26012368e+08, 1.47312520e+07, 4.49205996e+08,
       1.17694943e+08, 7.73060443e+08, 2.72976696e+08, 1.82219625e+09,
       1.96813905e+08, 5.23920029e+11, 5.22248130e+08, 1.40384813e+11,
       2.96071609e+10, 1.47506971e+10, 4.88820625e+09, 1.05212424e+09,
       4.69851670e+09, 1.15905686e+09, 1.02689261e+10, 1.68445302e+09,
       5.30349932e+11])

In [ ]:
(train.T).dot(train).dot(theta2).dot()

In [319]:
(train.T).dot(label)

array([2.64144946e+08, 1.46158857e+10, 1.93582539e+10, 3.08320594e+12,
       1.73789637e+09, 1.46265662e+09, 5.22530944e+11, 5.25505719e+11,
       3.73343366e+10, 1.37613191e+11, 1.20830185e+10, 1.60818300e+11,
       3.10514510e+11, 3.34249040e+11, 1.07813489e+11, 1.39949116e+09,
       4.43462020e+11, 1.26012368e+08, 1.47312520e+07, 4.49205996e+08,
       1.17694943e+08, 7.73060443e+08, 2.72976696e+08, 1.82219625e+09,
       1.96813905e+08, 5.23920029e+11, 5.22248130e+08, 1.40384813e+11,
       2.96071609e+10, 1.47506971e+10, 4.88820625e+09, 1.05212424e+09,
       4.69851670e+09, 1.15905686e+09, 1.02689261e+10, 1.68445302e+09,
       5.30349932e+11])

In [333]:
r = np.linalg.eig((train.T).dot(train))

In [339]:
t = r[0] / r[0].sum() * 100

In [337]:
r[1].shape

(37, 37)

In [340]:
t

array([9.54357778e+01, 3.95762480e+00, 1.62504384e-01, 1.46959419e-01,
       1.20253519e-01, 1.04610825e-01, 2.17332323e-02, 1.39928918e-02,
       1.29254601e-02, 9.79238344e-03, 6.01691778e-03, 1.77098748e-03,
       1.45459815e-03, 1.31064296e-03, 1.21040700e-03, 6.64300665e-04,
       6.50922356e-04, 3.63103358e-04, 1.31582476e-04, 1.22012740e-04,
       6.99025291e-05, 5.52867576e-05, 3.09290977e-06, 4.04962429e-07,
       3.69362724e-07, 2.68651996e-07, 1.22986336e-07, 1.03223279e-07,
       7.55395588e-08, 6.11558772e-08, 4.47593031e-08, 3.34688119e-08,
       1.28097982e-08, 1.98320935e-08, 1.77493810e-13, 3.15425064e-16,
       5.86578427e-17])

In [341]:
r[1][0]

array([-5.08725607e-05, -2.12768014e-04, -1.26531499e-04,  8.98176187e-06,
        1.33130821e-05, -1.14436348e-05, -8.02560504e-06,  1.43060484e-05,
        7.67617370e-06, -1.50240239e-05,  7.47498230e-06, -2.58159220e-05,
        1.41410203e-05, -1.71964290e-05,  2.50164797e-05,  2.39592705e-05,
       -5.16069805e-06,  5.46213780e-06,  4.52881634e-05, -2.76369686e-04,
       -2.86459594e-04,  1.36796410e-04, -3.45934537e-05, -1.25802433e-05,
       -3.74560262e-06,  8.31362028e-06, -2.11076608e-05, -2.87583734e-05,
        2.13483890e-06,  1.22221297e-04, -2.23840177e-05, -1.86363418e-04,
        1.18651385e-04,  4.95885283e-06,  9.99999843e-01, -4.23784910e-07,
       -3.78542259e-06])

In [342]:
train

array([[1.000e+00, 6.000e+01, 6.500e+01, ..., 0.000e+00, 2.000e+00,
        2.008e+03],
       [1.000e+00, 2.000e+01, 8.000e+01, ..., 0.000e+00, 5.000e+00,
        2.007e+03],
       [1.000e+00, 6.000e+01, 6.800e+01, ..., 0.000e+00, 9.000e+00,
        2.008e+03],
       ...,
       [1.000e+00, 7.000e+01, 6.600e+01, ..., 2.500e+03, 5.000e+00,
        2.010e+03],
       [1.000e+00, 2.000e+01, 6.800e+01, ..., 0.000e+00, 4.000e+00,
        2.010e+03],
       [1.000e+00, 2.000e+01, 7.500e+01, ..., 0.000e+00, 6.000e+00,
        2.008e+03]])

In [348]:
ntrain = (train[:,1:] - train[:,1:].mean(0))/train[:,1:].std(0)

In [350]:
ntrain = np.hstack((np.ones((ntrain.shape[0],1)),ntrain))

In [351]:
ntrain

array([[ 1.        ,  0.07337496, -0.22937175, ..., -0.08768781,
        -1.5991111 ,  0.13877749],
       [ 1.        , -0.87256276,  0.4519361 , ..., -0.08768781,
        -0.48911005, -0.61443862],
       [ 1.        ,  0.07337496, -0.09311018, ..., -0.08768781,
         0.99089135,  0.13877749],
       ...,
       [ 1.        ,  0.30985939, -0.18395123, ...,  4.95311151,
        -0.48911005,  1.64520971],
       [ 1.        , -0.87256276, -0.09311018, ..., -0.08768781,
        -0.8591104 ,  1.64520971],
       [ 1.        , -0.87256276,  0.22483348, ..., -0.08768781,
        -0.1191097 ,  0.13877749]])

In [352]:
nlabel = (label - label.mean()) / label.std()

In [354]:
meanl = label.mean()
stdl = label.std()

In [355]:
theta2 = np.linalg.inv((ntrain.T).dot(ntrain)).dot(ntrain.T).dot(nlabel)

In [356]:
theta2

array([ 6.76542156e-17, -1.05260980e-01, -5.17399499e-02,  1.89115778e-02,
        2.07091341e-01,  8.80349906e-02,  1.48562937e-01,  2.57303395e-02,
        2.85127270e-02,  5.03260130e-01,  8.88808227e-02,  3.81695596e-01,
       -3.03605187e-01,  7.55564028e-01,  8.46762177e-01,  9.71465386e-02,
       -6.43673649e-01,  6.11119728e-02,  6.12197302e-03,  2.39047739e-02,
       -1.20205881e-02, -1.03638100e-01, -3.38526641e-02,  1.03561930e-01,
        3.21760826e-02,  3.65806777e-02,  1.05647982e-01, -1.13977665e-02,
        3.78865374e-02, -2.39374763e-03,  9.09583629e-03,  7.56128301e-03,
        3.92939025e-02, -1.47031562e-02, -4.55846929e-03, -1.70401614e-03,
       -1.30430150e-02])

In [357]:
(ntrain.T).dot(ntrain).dot(theta2)

array([ 1.43672306e-13, -1.20598610e+02,  4.44573842e+02,  3.39082982e+02,
        1.08920554e+03, -1.00856190e+02,  7.51762530e+02,  7.22022418e+02,
        6.41945020e+02,  6.22511057e+02, -8.23866638e+01,  2.74525693e+02,
        8.93400098e+02,  8.80516361e+02,  4.45904185e+02, -1.41661496e+01,
        1.01689406e+03,  3.59647402e+02, -2.26721363e+01,  7.97844690e+02,
        4.00880789e+02,  2.40748297e+02, -1.82760945e+02,  7.62018239e+02,
        6.59195702e+02,  6.75419804e+02,  9.02664360e+02,  8.84402109e+02,
        4.68763223e+02,  4.51480745e+02, -1.97169488e+02,  6.55889731e+01,
        1.55537021e+02,  1.39455278e+02, -2.76724519e+01,  6.21913737e+01,
       -4.24914574e+01])

In [358]:
(ntrain.T).dot(nlabel)

array([ 1.82964754e-13, -1.23012688e+02,  4.88787764e+02,  3.85079352e+02,
        1.15443758e+03, -1.13630671e+02,  7.63168613e+02,  7.40113818e+02,
        6.93614661e+02,  5.63979674e+02, -1.66063673e+01,  3.13032236e+02,
        8.95520762e+02,  8.84241212e+02,  4.66067658e+02, -3.73721445e+01,
        1.03423736e+03,  3.31484880e+02, -2.45840418e+01,  8.18288714e+02,
        4.14655128e+02,  2.45507084e+02, -1.98356796e+02,  7.78968900e+02,
        6.81482597e+02,  6.86223953e+02,  9.34677169e+02,  9.09898132e+02,
        4.73481395e+02,  4.60992136e+02, -1.87659519e+02,  6.50698557e+01,
        1.62656261e+02,  1.34862973e+02, -3.09261897e+01,  6.77678579e+01,
       -4.22125106e+01])

In [370]:
ntest = (test[:,1:] - test[:,1:].mean(0)) / test[:,1:].std(0)
ntest = np.hstack((np.ones((ntest.shape[0],1)),ntest))

In [371]:
ntest.shape

(1459, 37)

In [373]:
m = ntest.shape[0]
result = np.zeros((m,1))
for i in range(m):
    x = ntest[i,:].reshape((1,-1))
    result[i,0] = x.dot(theta2.reshape((-1,1)))

In [376]:
result = (result * stdl) + meanl

In [377]:
result

array([[122440.04857585],
       [160515.55941893],
       [190478.47628279],
       ...,
       [176285.24464753],
       [113531.73348323],
       [259690.04880048]])

In [378]:
ret = pd.DataFrame(columns=['Id', 'SalePrice'])

ret['Id'] = c
ret['SalePrice'] = result

In [379]:
ret.to_csv('ret2.csv', index=False)